skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
ecv_oracle = "2t815MdALeVCAKYbkpVFyjNfoF3U7PKLaAirNbNT73LL"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
